### PR TITLE
Create parent directory for pages and separate styles

### PR DESCRIPTION
**Pull request by DakoMumladze**
This fix is related to #68 

Created new file system, moved code from pages to components and exported these components to pages.

### CODE REVIEW

**Comment by Anzormumladze** [comment]
eslint გაუშვი და ისე დაფუშე

**Comment by shavidzet** [comment]
> eslint გაუშვი და ისე დაფუშე

`WIP` label აქვს შესაბამისად რაც უნდა ის უქნია @DakoMumladze-ს იქამდე სანამ WIPს არ მოაძრობს :v:

**Comment by shavidzet** [comment]
Based on latest commit (https://github.com/task-er/tasker-monorepo/pull/72/commits/869d4a896123b684e04086dbbc39123392510a23) we have all routes under parent directory as we talked in our issue(#68), but there was 1 problem with `/` uri, gatsby doesn't generate automatically `/index` dir as `/`(root) URI, that's why we moved `pages/index.js` file under `/components/home` dir.

related issue with gatsby: https://github.com/gatsbyjs/gatsby/issues/7363#issue-351011214
near future plans to improve router: https://github.com/task-er/tasker-monorepo/pull/76

**Comment by shavidzet** [comment]
Latest changes(commit: https://github.com/task-er/tasker-monorepo/pull/72/commits/9f4143c85992bccbad1dc05d4fef6bc4b4943cdd) has been reverted, because gatsby can't bundle static pages, you can check CI logs - https://app.circleci.com/jobs/github/task-er/tasker-monorepo/218

Above issue is happening because gatsby tries to generate new page from `src/pages/forgot-password/style.js` and this is completely different what we expected.

Until we will have more controlled router we stick to implement pages in `/components` dir.

**Pull request merged**
